"""empty message

Revision ID: 217b3b28b2e6
Revises: 48c89a6b8d73
Create Date: 2023-11-18 13:43:21.240556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '217b3b28b2e6'
down_revision = '48c89a6b8d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_bevindingen_templates', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bevtype', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_bevindingen_templates', schema=None) as batch_op:
        batch_op.drop_column('bevtype')

    # ### end Alembic commands ###
