"""empty message

Revision ID: 48c89a6b8d73
Revises: 
Create Date: 2023-11-18 13:09:38.788834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48c89a6b8d73'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_agents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=255), nullable=True),
    sa.Column('uitwerken', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent', sa.String(length=255), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('command', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('db_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('naam', sa.String(length=255), nullable=True),
    sa.Column('uitwerken', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('db_notes')
    op.drop_table('db_commands')
    op.drop_table('db_agents')
    # ### end Alembic commands ###
