"""empty message

Revision ID: b585a7cdf86a
Revises: 
Create Date: 2023-08-30 09:40:53.120914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b585a7cdf86a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_bevinding', schema=None) as batch_op:
        batch_op.add_column(sa.Column('basescore', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('cvss', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('db_bevinding', schema=None) as batch_op:
        batch_op.drop_column('cvss')
        batch_op.drop_column('basescore')

    # ### end Alembic commands ###
